sudo: required
language: generic
services:
  - docker


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "techfeedy"
  env: "Techfeedy-env"
  bucket_name: "elasticbeanstalk-us-east-1-674449595317"
  bucket_path: "techfeedy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY